add rust sdk 29

diff --git a/.github/workflows/flatpak.yml b/.github/workflows/flatpak.yml
--- a/.github/workflows/flatpak.yml
+++ b/.github/workflows/flatpak.yml
@@ -58,7 +58,7 @@ jobs:
     - name: Debug Cargo Build Output
       run: |
         echo "Checking Cargo output directory..."
-        find /tmp/build -type f -name "puter" || echo "Binary not found!"
+        find /github/home/.cache/.flatpak/org.gnome.Sdk/tmp/build -type f -name "puter" || echo "Binary not found!"
         find $HOME -type f -name "puter" 2>/dev/null || echo "Binary not found in home!"
     
     - name: Debug data directory
@@ -72,7 +72,7 @@ jobs:
         mkdir -p flatpak-build/share/applications
         mkdir -p flatpak-build/share/icons/hicolor/scalable/apps
         mkdir -p flatpak-build/share/metainfo
-        cp /tmp/build/target/release/puter flatpak-build/bin/ || echo "Binary not found in /tmp/build/target/release/"
+        cp /github/home/.cache/.flatpak/org.gnome.Sdk/tmp/build/target/release/puter flatpak-build/bin/ || echo "Binary not found in /github/home/.cache/.flatpak/org.gnome.Sdk/tmp/build/target/release/"
         cp data/lol.janjic.puter.desktop flatpak-build/share/applications/
         cp data/icons/lol.janjic.puter.svg flatpak-build/share/icons/hicolor/scalable/apps/
         cp data/lol.janjic.puter.metainfo.xml flatpak-build/share/metainfo/
